//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformaticaIndustrial.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulo
    {
        public articulo()
        {
            this.boms = new HashSet<bom>();
            this.boms1 = new HashSet<bom>();
        }
    
        public int articulo_id { get; set; }
        public int descripcion_id { get; set; }
        public float precio_std { get; set; }
        public string descripcion { get; set; }
        public int tipo_articulo { get; set; }
        public int unidad_med { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public Nullable<int> registro_id { get; set; }
    
        public virtual descripcion descripcion1 { get; set; }
        public virtual registro registro { get; set; }
        public virtual tipo_articulo tipo_articulo1 { get; set; }
        public virtual unidad_med unidad_med1 { get; set; }
        public virtual ICollection<bom> boms { get; set; }
        public virtual ICollection<bom> boms1 { get; set; }
    }
}
