//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformaticaIndustrial.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class bom
    {
        public int bom_id { get; set; }
        public int articulo_padre { get; set; }
        public int articulo_hijo { get; set; }
        public float cantidad { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public int um_id { get; set; }
        public int registro_id { get; set; }
    
        public virtual articulo articulo { get; set; }
        public virtual articulo articulo1 { get; set; }
        public virtual registro registro { get; set; }
        public virtual unidad_med unidad_med { get; set; }
    }
}
