//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformaticaIndustrial.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class descripcion
    {
        public descripcion()
        {
            this.articuloes = new HashSet<articulo>();
            this.externos = new HashSet<externo>();
            this.rols = new HashSet<rol>();
            this.tipo_articulo = new HashSet<tipo_articulo>();
            this.tipo_externos = new HashSet<tipo_externos>();
            this.unidad_med = new HashSet<unidad_med>();
        }
    
        public int descripcion_id { get; set; }
        public int lenguaje_id { get; set; }
        public string descripcion_str { get; set; }
    
        public virtual ICollection<articulo> articuloes { get; set; }
        public virtual ICollection<externo> externos { get; set; }
        public virtual lenguaje lenguaje { get; set; }
        public virtual ICollection<rol> rols { get; set; }
        public virtual ICollection<tipo_articulo> tipo_articulo { get; set; }
        public virtual ICollection<tipo_externos> tipo_externos { get; set; }
        public virtual ICollection<unidad_med> unidad_med { get; set; }
    }
}
