//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformaticaIndustrial.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class lenguaje
    {
        public lenguaje()
        {
            this.descripcions = new HashSet<descripcion>();
            this.usuarios = new HashSet<usuario>();
        }
    
        public int lenguaje_id { get; set; }
        public string lenguaje_desc { get; set; }
    
        public virtual ICollection<descripcion> descripcions { get; set; }
        public virtual ICollection<usuario> usuarios { get; set; }
    }
}
