//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformaticaIndustrial.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<art_sustituto> art_sustituto { get; set; }
        public DbSet<articulo> articuloes { get; set; }
        public DbSet<bom> boms { get; set; }
        public DbSet<descripcion> descripcions { get; set; }
        public DbSet<externo> externos { get; set; }
        public DbSet<lenguaje> lenguajes { get; set; }
        public DbSet<registro> registros { get; set; }
        public DbSet<rol> rols { get; set; }
        public DbSet<stock> stocks { get; set; }
        public DbSet<tipo_articulo> tipo_articulo { get; set; }
        public DbSet<tipo_externos> tipo_externos { get; set; }
        public DbSet<unidad_med> unidad_med { get; set; }
        public DbSet<usuario> usuarios { get; set; }
    }
}
