//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformaticaIndustrial.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class registro
    {
        public registro()
        {
            this.articuloes = new HashSet<articulo>();
            this.boms = new HashSet<bom>();

            this.terminal = "local";
            this.usuario_id = 1;
        }
    
        public int registro_id { get; set; }
        public System.DateTime fecha_mod { get; set; }
        public string terminal { get; set; }
        public int usuario_id { get; set; }
    
        public virtual ICollection<articulo> articuloes { get; set; }
        public virtual ICollection<bom> boms { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
