//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformaticaIndustrial
{
    using System;
    using System.Collections.Generic;
    
    public partial class unidad_med
    {
        public unidad_med()
        {
            this.articuloes = new HashSet<articulo>();
            this.boms = new HashSet<bom>();
        }
    
        public int unidad_id { get; set; }
        public int descripcion_id { get; set; }
        public string factor_n { get; set; }
    
        public virtual ICollection<articulo> articuloes { get; set; }
        public virtual ICollection<bom> boms { get; set; }
        public virtual descripcion descripcion { get; set; }
    }
}
